apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-elev-dummy-adapter
  namespace: fintlabs-no
  labels:
    app.kubernetes.io/name: fint-elev-dummy-adapter
    app.kubernetes.io/instance: fint-elev-dummy-adapter_fintlabs_no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: adapter
    app.kubernetes.io/part-of: fint-core
    fintlabs.no/team: core
    fintlabs.no/org-id: fintlabs.no
spec:
  port: '8080'
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-elev-dummy-adapter:latest
  imagePullPolicy: Always
  envFrom:
    - secretRef:
        name: fint-elev-dummy-adapter
  resources:
    limits:
      memory: 512Mi
      cpu: 500m
    requests:
      memory: 256Mi
      cpu: 250m
  restartPolicy: Always
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
